#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="clear-app-buckets"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/.env

BUCKETS=$(aws s3 ls | awk -F ' ' '{ for(i=NF; i>=NF; --i) printf "%s ", $i; }')

# Example Usage:
# >$     clear-app-ecrs

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

# COMPONENTS=("alpha" "beta" "gamma" "delta" "epsilon")

for COMPONENT in ${COMPONENTS[@]}
do 
    aws ecr delete-repository \
        --repository-name "${APPLICATION}-lambda-${COMPONENT}" \
        --force
done

aws ecr delete-repository \
    --repository-name "${APPLICATION}-postgres" \
    --force
