#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="clone-bb-repos"
SCRIPT_DES=$'Clone over Bitbucket repositories into CodeCommit repositories provisioned through ${application}-RepoStack'
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/.env

# Example Usage:
# >$     clone-bb-repos --environments Dev,Prod,Staging

# NOTE: ``--environments`` is a comma separated list with no spaces.

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --environments)
            IFS=',' read -ra ENVIRONMENTS <<< "$2"
            shift
            shift
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

REPOS=("frontend" "backend")

mkdir ./tmp
cd tmp

for repo in ${REPOS[@]}
do
    case $repo in
        backend)
            BB_REPO="gateway-lambdas"
            CC_REPO="$APPLICATION-backend"
            ;;
        frontend)
            BB_REPO="cloudfront-s3"
            CC_REPO="$APPLICATION-frontend"
            ;;
    esac

    git clone git@bitbucket.org:Makpar/$BB_REPO.git
    mkdir $CC_REPO

    for environment in ${ENVIRONMENTS[@]}
    do
        cd $BB_REPO && git checkout $environment
        cd .. && cp -ap ./$BB_REPO/. ./$CC_REPO
        cd $CC_REPO && git remote remove origin 
        git remote add origin ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/$CC_REPO
        git add .
        git commit -m 'init commit'
        git push --set-upstream origin $environment
        cd ..
        rm -rf $CC_REPO
        mkdir $CC_REPO
    done
done

REPOS=("cloud-formation" "docker-images" "test-harness")

for repo in ${REPOS[@]}
do
    case $repo in
        cloud-formation)
            BB_REPO="cloud-formation"
            CC_REPO="$APPLICATION-cloudformation"
            ;;
        docker-images)
            BB_REPO="docker-images"
            CC_REPO="$APPLICATION-docker-images"
            ;;
        test-harness)
            BB_REPO="test-harness"
            CC_REPO="$APPLICATION-test-harness"  
            ;;
    esac

    git clone git@bitbucket.org:Makpar/$BB_REPO.git
    mkdir $CC_REPO

    cd $BB_REPO && git checkout master
    cd .. && cp -ap ./$BB_REPO/. ./$CC_REPO
    cd $CC_REPO && git remote remove origin 
    git remote add origin ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/$CC_REPO
    git add .
    git commit -m 'init commit'
    git push --set-upstream origin master
    cd ..
done


cd .. && rm -rf ./tmp