#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="clone-bb-repos"
SCRIPT_DES=$'Clone over Bitbucket repositories into CodeCommit repositories provisioned through ${application}-RepoStack'
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/.env

# Example Usage:
# >$     create-branch-rule

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

RULE_NAME="$APPLICATION-environment-branch-restricted-access"
RULE_DESCRIPTION="Requires one developer from the team to approve the pull request if the destination branch is one of the environment branches: Prod, Staging or Dev"
RULE_TEMPLATE="{\"Version\": \"2018-11-08\",\"DestinationReferences\": [\"refs/heads/Dev\",\"refs/heads/Staging\", \"refs/heads/Prod\"],\"Statements\": [{\"Type\": \"Approvers\",\"NumberOfApprovalsNeeded\": 1,\"ApprovalPoolMembers\": [\"arn:aws:iam::$AWS_ACCOUNT_ID:user/$APPLICATION/tklock\", \"arn:aws:iam::$AWS_ACCOUNT_ID:user/$APPLICATION/pconfrancesco\", \"arn:aws:iam::$AWS_ACCOUNT_ID:user/$APPLICATION/gmoore\", \"arn:aws:iam::$AWS_ACCOUNT_ID:user/$APPLICATION/pngo\", \"arn:aws:iam::$AWS_ACCOUNT_ID:user/$APPLICATION/mpinardi\", \"arn:aws:iam::$AWS_ACCOUNT_ID:user/$APPLICATION/imcnutt\"]}]}"

aws codecommit create-approval-rule-template \
                --approval-rule-template-name "$RULE_NAME" \
                --approval-rule-template-description "$RULE_DESCRIPTION" \
                --approval-rule-template-content "$RULE_TEMPLATE"

aws codecommit batch-associate-approval-rule-template-with-repositories \
                --repository-names "$APPLICATION-frontend" "$APPLICATION-backend" \
                --approval-rule-template-name "$RULE_NAME"