#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="invalidate-cache"
SCRIPT_DES=$'Invalidate the CloudFront cache. Use after deploying to S3 bucket for latest changes to show up.'
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/.env

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --action)
            ACTION="$2"
            shift
            shift 
            ;;
        --help)
            help
            exit 0
            ;;
        --environment)
            ENVIRONMENT="$2"
            shift
            shift
            ;;
        --page)
            PAGE="$2"
            shift
            shift
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

# NOTE: make sure to copy .sample.env into a new .env file and set the 
#   CLOUDFRONT_DISTRIBUTION_ID to the cache you want to invalidate.

CLOUDFRONT_DISTRIBUTION_ID=$($SCRIPT_DIR/retrieve-cloudfront-id --page $PAGE --environment $ENVIRONMENT)
aws cloudfront create-invalidation \
        --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
        --paths "/*"