#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="repo-stack"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../../..
source $PROJECT_DIR/env/.env

# Example Usage:
# >$     coverage-stack --action <create | update | delete> 

#   NOTE: ``--action`` defaults to `create` if not supplied

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
       key="$1"
       case $key in
            --action|-action|--a|-a)
                ACTION="$2"
                shift
                shift 
                ;;
            --help|-help|--h|-h)
                help
                exit 0
                ;;
            *)
                log "Input not understood. See \e[3m--help\e[0m for information on using this command."
                exit 1
                ;;
       esac
done

if [ -z "$ACTION" ]
then
    log "No \e[3m--action\e[0m specified. Defaulting to \e[1mcreate\e[0m"
    ACTION="create"
fi

cp $PROJECT_DIR/templates/devops/coverage.yml ./coverage.yml

if [ "$ACTION" == "create" ]
then
    aws cloudformation create-stack \
        --stack-name "${APPLICATION^}-${COVERAGE_STACK}" \
        --template-body file://coverage.yml \
        --parameters ParameterKey=applicationName,ParameterValue=$APPLICATION \
                        ParameterKey=domainName,ParameterValue=$DOMAIN \
                        ParameterKey=hostedZoneId,ParameterValue=$HOSTED_ZONE_ID \
                        ParameterKey=certificateArn,ParameterValue="arn:aws:acm:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:certificate/$CERTIFICATE_ID"

elif [ "$ACTION" == "update" ]
then
    aws cloudformation update-stack \
        --stack-name "${APPLICATION^}-${COVERAGE_STACK}" \
        --template-body file://coverage.yml \
        --parameters ParameterKey=applicationName,ParameterValue=$APPLICATION \
                        ParameterKey=domainName,ParameterValue=$DOMAIN \
                        ParameterKey=hostedZoneId,ParameterValue=$HOSTED_ZONE_ID \
                        ParameterKey=certificateArn,ParameterValue="arn:aws:acm:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:certificate/$CERTIFICATE_ID"
         
elif [ "$ACTION" == "delete" ]
then
    aws cloudformation delete-stack \
        --stack-name "${APPLICATION^}-${COVERAGE_STACK}"
else
    log "Action not understood"
fi

rm ./coverage.yml