#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="repo-stack"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../../..
source $PROJECT_DIR/.env

# Example Usage:
# >$     devops-stack --environment <Dev | Prod | Test | Staging> \
#                   --action <create | update | delete> 

#   NOTE: ``--action`` defaults to `create` if not supplied

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
       key="$1"
       case $key in
                --action)
                    ACTION="$2"
                    shift
                    shift 
                    ;;
                --help)
                    help
                    exit 0
                    ;;
                *)
                    log "Input not understood. See \e[3m--help\e[0m for information on using this command."
                    exit 1
                    ;;
       esac
done

if [ -z "$ACTION" ]
then
    ACTION="create"
fi

cp $PROJECT_DIR/templates/devops/sonar.yml ./sonar.yml

if [ "$ACTION" == "create" ]
then
    aws cloudformation create-stack \
        --stack-name "${APPLICATION^}-${SONAR_STACK}" \
        --template-body file://sonar.yml \
        --parameters ParameterKey=vpcStack,ParameterValue="${APPLICATION^}-${VPC_STACK}-Dev"

elif [ "$ACTION" == "update" ]
then
    aws cloudformation update-stack \
        --stack-name "${APPLICATION^}-${SONAR_STACK}" \
        --template-body file://sonar.yml \
        --parameters ParameterKey=vpcStack,ParameterValue="${APPLICATION^}-${VPC_STACK}-Dev"
         
elif [ "$ACTION" == "delete" ]
then
    aws cloudformation delete-stack \
        --stack-name "${APPLICATION^}-${SONAR_STACK}"
else
    log "Action not understood"
fi

rm ./sonar.yml