AWSTemplateFormatVersion: "2010-09-09"

Description: 'Provisions resources for the Sonar service deployed into applicationName-ClusterStack-environmentName. A task definition is created with the official SonarQube iamge. The task definition is used to spin up a service instance of SonarQube.'

Parameters:
  ## CROSS STACK REFERENCES
  iamStack:
    Type: String
    Default: Innolab-IAMStack
    Description: Name of the IAM Cross Stack reference
  repoStack:
    Type: String
    Default: Innolab-RepoStack
    Description: Name of the Repo Cross Stack reference
  vpcStack:
    Type: String
    Default: Innolab-VPCStack-Dev
    Description: Name of the VPC Cross Stack reference
  clusterStack:
    Type: String
    Default: Innolab-ClusterStack-Dev
  ## APPLICATION CONFIGURATION
  applicationName:
    Type: String
    Default: innolab
    Description: The name of the application being deployed.
  environmentName:
    Type: String
    Default: Dev
    Description: The environment into which the application is being deployed.
  ## SERVICE CONFIGURATION
  domain:
    Type: String
    Default: makpar-innovation.net
    Description: Domain for the application cluster
  port:
    Type: Number
    Default: 9000
    Description: Port mapping for sonar service 
  tag:
    Type: String
    Default: Dev
    Description: Image tag for the front service ECR

Mappings:
  BranchMap:
    Dev: 
      branch:  "dev"
      subdomain: "-dev"
    Test: 
      branch: "test"
      subdomain: "-test"
    Staging: 
      branch: "staging"
      subdomain: "-staging"
    Prod: 
      branch: "prod"
      subdomain: ""

Resources:
  SonarLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${applicationName}/${environmentName}/sonar/"

  AutoScalingSonarTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 3
      ResourceId: !Join ['/', [service, Fn::ImportValue: !Sub "${clusterStack}-Cluster", !GetAtt SonarService.Name]]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: 
        Fn::ImportValue: !Sub "${iamStack}-ECSScalingRoleArn"

  AutoScalingSonarPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "service/${applicationName}-${environmentName}-cluster/${applicationName}-${environmentName}-sonar"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingSonarTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        # Keep things at or lower than 50% CPU utilization, for example
        TargetValue: 50

  SonarTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      # will look for a 200 status code by default unless specified otherwise
      HealthCheckPath: /api/system/status
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Sub "${applicationName}-${environmentName}-sonar-target"
      Port: !Ref port
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # default is 300
      TargetType: ip
      VpcId: 
        Fn::ImportValue: !Sub "${vpcStack}-VPC"
  
  SonarLoadBalancerListenerCondition:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Priority: 2
      ListenerArn: 
        Fn::ImportValue: !Sub ${clusterStack}-PublicLoadBalancerListenerARN
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values: 
              - !Sub "${applicationName}-sonar.${domain}"
      Actions:
        - Type: forward
          TargetGroupArn: !Ref SonarTargetGroup

  SonarTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: SonarLogGroup
    Properties:
      Family: !Sub "${applicationName}-${environmentName}-sonar-task-definition"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 1024
      Memory: 4096
      ExecutionRoleArn: 
        Fn::ImportValue: !Sub "${iamStack}-ECSTaskExecutionRoleArn"
      ContainerDefinitions:
        - Name: !Sub ${applicationName}-${environmentName}-sonar
          Image: sonarqube:latest
          PortMappings:
            - ContainerPort: !Ref port
          # Command: 
          #   - -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref SonarLogGroup
              awslogs-stream-prefix: ecs

  SonarService:
    Type: AWS::ECS::Service
    Properties: 
      ServiceName: !Sub ${applicationName}-${environmentName}-sonar
      Cluster: 
        Fn::ImportValue: !Sub ${clusterStack}-Cluster
      TaskDefinition: !Ref SonarTaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      # This may need to be adjusted if the container takes a while to start up
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration:
          # change to DISABLED if you're using private subnets that have access to a NAT gateway
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: !Sub ${vpcStack}-PublicSubnetA
            - Fn::ImportValue: !Sub ${vpcStack}-PublicSubnetB
          SecurityGroups:
            - Fn::ImportValue: !Sub ${clusterStack}-SecurityGroup
      LoadBalancers:
        - ContainerName: !Sub ${applicationName}-${environmentName}-sonar
          ContainerPort: !Ref port
          TargetGroupArn: !Ref SonarTargetGroup
      ServiceRegistries:
        - RegistryArn: !GetAtt SonarDiscoveryService.Arn
          Port: !Ref port

  SonarDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: !Sub "Discovery service for the ${applicationName}-${environmentName}-sonar service"
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: !Sub ${applicationName}-${environmentName}-sonar-discovery
      NamespaceId: 
        Fn::ImportValue: !Sub ${clusterStack}-Namespace

Outputs:
  SonarTargetGroup:
    Value: !GetAtt SonarTargetGroup.TargetGroupName
    Description: Name of first sonar target group
    Export:
      Name: !Sub ${AWS::StackName}-SonarTargetGroup
  SonarServiceName:
    Value: !GetAtt SonarService.Name
    Description: Name of the sonar service
    Export: 
      Name: !Sub ${AWS::StackName}-SonarServiceName
  SonarServiceArn:
    Value: !Ref SonarService
    Description: Arn of the sonar service
    Export: 
      Name: !Sub ${AWS::StackName}-SonarServiceARN
  SonarTaskDefinitionArn:
    Value: !Ref SonarTaskDefinition
    Description: Arn of the sonar task definition
    Export:
      Name: !Sub ${AWS::StackName}-SonarTaskARN
        