#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="vpc-stack"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../../..
source $PROJECT_DIR/env/.env

# Example Usage:
# >$     vpc-stack --action <create | update | delete>
#                   --environment <Dev | Staging | Prod>
#                   --bastion-host <true | false>

#   NOTE: ``--action`` defaults to `create` if not supplied
#   NOTE: This script will generate an SSH key with the name given by the environment
#           variable $SSH_KEY_NAME in your user's *~/.ssh/* directory. The private key
#           in this directory can be used to initiate an SSH tunnel with the RDS instance
#           through the NAT Instance bastion host.
#   NOTE: '`-bastion-host` will default to true if not provided.

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --action|-action|--a|-a)
            ACTION="$2"
            if [ $ACTION != "create" ] || [ $ACTION != "update" ] || [ $ACTION != "delete" ]
            then
                log "'action==$ACTION' not in allowed values: <create | update | delete>"
                exit 1
            fi
            shift
            shift 
            ;;
        --environment|-environment|--env|-env|--e|-e)
            ENVIRONMENT="$2"
            if [ "$ENVIRONMENT" != "Dev" ] || [ "$ENVIRONMENT" != "Staging" ] || [ "$ENVIRONMENT" != "Prod" ]
            then
                log "'environment==$ENVIRONMENT' not in allowed values: <Dev | Staging | Prod>"
                exit 1
            fi
            shift
            shift
            ;;
        --bastion-host|-bastion-host|--bh|-bh)
            BASTION_HOST="$2"
            if [ $BASTION_HOST != "true" ] || [$BASTION_HOST != "false"]
            then 
                log "'bastion-host==$BASTION_HOST' not in allowed values: <true | false>"
                exit 1
            fi
            shift
            shift
            ;;
        --help|-help|--h|-h)
            help
            exit 0
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

if [ -z "$ACTION" ]
then
    log "No \e[3m--action\e[0m specified. Defaulting to \e[1mcreate\e[0m"
    ACTION="create"
fi

if [ -z "$BASTION_HOST" ]
then 
    log "No \e[3m--bastion-host\e[0m specified. Defaulting to \e[1mtrue\e[0m"
    BASTION_HOST="true"
fi

cp $PROJECT_DIR/templates/app/vpc.yml ./vpc.yml

if [ "$ACTION" == "create" ]
then
    ssh-keygen \
        -t rsa \
        -C "${APPLICATION}_${SSH_KEY_NAME}_${ENVIRONMENT}" \
        -f ~/.ssh/"${APPLICATION}_${SSH_KEY_NAME}_${ENVIRONMENT}"

    aws ec2 import-key-pair \
        --key-name "${APPLICATION}_${SSH_KEY_NAME}_${ENVIRONMENT}"  \
        --public-key-material fileb://~/.ssh/"${APPLICATION}_${SSH_KEY_NAME}_${ENVIRONMENT}.pub"

    aws cloudformation create-stack \
        --stack-name "${APPLICATION^}-${VPC_STACK}-${ENVIRONMENT}" \
        --template-body file://vpc.yml \
        --parameters ParameterKey=environmentName,ParameterValue=$ENVIRONMENT \
                     ParameterKey=dbKeyName,ParameterValue="${APPLICATION}_${SSH_KEY_NAME}_${ENVIRONMENT}" \
                     ParameterKey=applicationName,ParameterValue=$APPLICATION \
                     ParameterKey=bastionHost,ParameterValue=$BASTION_HOST

elif [ "$ACTION" == "update" ]
then
    aws cloudformation update-stack \
        --stack-name "${APPLICATION^}-${VPC_STACK}-${ENVIRONMENT}" \
        --template-body file://vpc.yml \
        --parameters ParameterKey=environmentName,ParameterValue=$ENVIRONMENT \
                     ParameterKey=dbKeyName,ParameterValue="${APPLICATION}_${SSH_KEY_NAME}_${ENVIRONMENT}" \
                     ParameterKey=applicationName,ParameterValue=$APPLICATION \
                     ParameterKey=bastionHost,ParameterValue=$BASTION_HOST

elif [ "$ACTION" == "delete" ]
then
    aws cloudformation delete-stack \
        --stack-name "${APPLICATION^}-${VPC_STACK}-${ENVIRONMENT}"
    
    aws ec2 delete-key-pair \
        --key-name "${APPLICATION}_${SSH_KEY_NAME}_${ENVIRONMENT}"

fi

rm ./vpc.yml