#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="frontend-stack"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/.env

# Example Usage:
# >$     frontend-stack --environment <Dev | Prod | Test | Staging> \
#                       --action <create | update | delete>

#   NOTE: ``--action`` defaults to `create` if not supplied

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --action)
            ACTION="$2"
            shift
            shift 
            ;;
        --help)
            help
            exit 0
            ;;
        --environment)
            ENVIRONMENT="$2"
            shift
            shift
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

if [ -z "$ACTION" ]
then
    ACTION="create"
fi

cp $PROJECT_DIR/templates/frontend/frontend.yml ./frontend.yml

if [ "$ACTION" == "create" ]
then
    aws cloudformation create-stack \
        --stack-name "${FRONTEND_STACK}-${ENVIRONMENT}" \
        --template-body file://frontend.yml \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameters ParameterKey=environmentName,ParameterValue=$ENVIRONMENT \
                     # APPLICATION to lower case since S3 bucket name has to be all lowercase
                     ParameterKey=applicationName,ParameterValue=${APPLICATION,,} \
                     ParameterKey=domain,ParameterValue=$DOMAIN \
                     ParameterKey=subdomain,ParameterValue=$SUBDOMAIN \
                     ParameterKey=dnsStack,ParameterValue="$DNS_STACK-$ENVIRONMENT" \
                     ParameterKey=userStack,ParameterValue=$USER_STACK

elif [ "$ACTION" == "update" ]
then
    echo "$SUBDOMAIN"
    aws cloudformation update-stack \
        --stack-name "${FRONTEND_STACK}-${ENVIRONMENT}" \
        --template-body file://frontend.yml \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameters ParameterKey=environmentName,ParameterValue=$ENVIRONMENT \
                        # APPLICATION to lower case since S3 bucket name has to be all lowercase
                     ParameterKey=applicationName,ParameterValue=${APPLICATION,,} \
                     ParameterKey=domain,ParameterValue=$DOMAIN \
                     ParameterKey=subdomain,ParameterValue=$SUBDOMAIN \
                     ParameterKey=dnsStack,ParameterValue="$DNS_STACK-$ENVIRONMENT" \
                     ParameterKey=userStack,ParameterValue=$USER_STACK

elif [ "$ACTION" == "delete" ]
then
    aws cloudformation delete-stack \
        --stack-name "${FRONTEND_STACK}-${ENVIRONMENT}"
else
    log "Action not understood"
fi

rm ./frontend.yml