#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="clear-buckets"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/..
source $PROJECT_DIR/.env

BUCKETS=$(aws s3 ls | awk -F ' ' '{ for(i=NF; i>=NF; --i) printf "%s ", $i; }')

# Example Usage:
# >$     clear-buckets --environments Dev,Prod,Staging

# NOTE: ``--environments`` is a comma separated list with no spaces.

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --environments)
            IFS=',' read -ra ENVIRONMENTS <<< "$2"
            shift
            shift
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

for environment in ${ENVIRONMENTS[@]}
    do
        for bucket in ${BUCKETS[@]}
        do 
            if [ "${environment,,}" == "prod" ]
            then
                environment=""
            fi  

            if [[ "$bucket" == ${APPLICATION,,}* ]] 
            then
                log "Clearing $bucket S3 bucket"
                aws s3 rm s3://$bucket --recursive
            fi
        done
done