#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="install"
SCRIPT_DES=$'Build and install the \e[3mcf-deploy\e[0m CLI from source.'
PROJECT_DIR=$SCRIPT_DIR/..

if [ -d $PROJECT_DIR/src/dist ]
then
  rm -r $PROJECT_DIR/src/dist
fi

cd $PROJECT_DIR/python

python3 -m build

VERSION=$(cat $PROJECT_DIR/python/version.txt)

cd $PROJECT_DIR/python/dist

pip uninstall -y cf-deploy

pip install cf_deploy-${VERSION}-py3-none-any.whl
