#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="lambda-stack"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/..
source $PROJECT_DIR/.env

# Example Usage:
# >$     lambda-stack --components one | two | three | four --environment Dev

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
       key="$1"
       case $key in
              --components)
                     COMPONENTS="$2"
                     shift
                     shift
                     ;;
              --environment)
                     ENVIRONMENT="$2"
                     shift
                     shift
                     ;;
              --help)
                     help
                     exit 0
                     ;;
              *)
                     log "Input not understood. See \e[3m--help\e[0m for information on using this command."
                     exit 1
                     ;;
       esac
done

cp $PROJECT_DIR/lambda/lambda.yml ./lambda.yml

aws cloudformation create-stack \
       --stack-name "${LAMBDA_STACK}" \
       --template-body file://lambda.yml \
       --parameters ParameterKey=components,ParameterValue=$COMPONENTS \
       --parameters ParameterKey=environmentName,ParameterValue=$ENVIRONMENT \
       --parameters ParameterKey=userStack,ParameterValue=$USER_STACK \
       --parameters ParameterKey=vpcStack,ParameterValue=$VPC_STACK \
       --capabilities CAPABILITY_NAMED_IAM

rm ./lambda.yml