#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR=$SCRIPT_DIR/..

if [ -f $PROJECT_DIR/env/.env ]
then
    source $PROJECT_DIR/env/.env
fi

if ! command -v cfn-lint &> /dev/null
then
    pip install -r $PROJECT_DIR/src/requirements-dev.txt
fi

cfn-lint $PROJECT_DIR/src/innolab_deploy/templates/**/*.yml \
            --output-file $PROJECT_DIR/reports/cfn-lint/"$(date +'%m-%d-%Y')_report.json"