#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="rds-stack"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/..
source $PROJECT_DIR/.env

# Example Usage:
# >$     rds-stack --environment Dev

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
       key="$1"
       case $key in
                --help)
                    help
                    exit 0
                    ;;
                --environment)
                    ENVIRONMENT="$2"
                    shift
                    shift
                    ;;
                *)
                    log "Input not understood. See \e[3m--help\e[0m for information on using this command."
                    exit 1
                    ;;
       esac
done

cp $PROJECT_DIR/rds/rds.yml ./rds.yml

NAME_PARAMETER="/CCC/credentials/${ENVIRONMENT}/dbUsername"
PASSWORD_PARAMETER="/CCC/credentials/${ENVIRONMENT}/dbPassword"

# aws ssm put-parameter --name $NAME_PARAMETER --value $RDS_USERNAME --type SecureString
# aws ssm put-parameter --name $PASSWORD_PARAMETER --value $RDS_PASSWORD --type SecureString

# aws ssm put-parameter --cli-input-json "{\"Name\": \"$NAME_PARAMETER\", \"Value\": \"$RDS_USERNAME\", \"Type\": \"SecureString\"}"
# aws ssm put-parameter --cli-input-json "{\"Name\": \"$PASSWORD_PARAMETER\", \"Value\": \"$RDS_PASSWORD\", \"Type\": \"SecureString\"}"

aws secretsmanager create-secret --name "${ENVIRONMENT}-dbUsername" \
                                 --description "Database Username Secret for ${ENVIRONMENT} environment" \
                                 --secret-string $RDS_USERNAME

aws secretsmanager create-secret --name "${ENVIRONMENT}-dbPassword" \
                                 --description "Database Password Secret for ${ENVIRONMENT} environment" \
                                 --secret-string $RDS_PASSWORD

aws cloudformation create-stack \
    --stack-name "${RDS_STACK}" \
    --template-body file://rds.yml \
    --parameters ParameterKey=environmentName,ParameterValue=$ENVIRONMENT \
                 ParameterKey=vpcStack,ParameterValue=$VPC_STACK \
                 ParameterKey=dbUsername,ParameterValue=$RDS_USERNAME

rm ./rds.yml