#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="rds-stack"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/..
source $PROJECT_DIR/.env

# Execute this step after standing up the RDS stack to store the host URL provisioned in a Secret.

# Example Usage:
# >$     rds-host-secret --environment <Dev | Prod | Test>

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
       key="$1"
       case $key in
                --help)
                    help
                    exit 0
                    ;;
                --environment)
                    ENVIRONMENT="$2"
                    shift
                    shift
                    ;;
                *)
                    log "Input not understood. See \e[3m--help\e[0m for information on using this command."
                    exit 1
                    ;;
       esac
done

RDS_HOST=$(aws cloudformation describe-stacks | jq ".Stacks[] | select(.StackName==\"${RDS_STACK}-${ENVIRONMENT}\")" | jq '.Outputs[0].OutputValue')

aws secretsmanager create-secret --name "${ENVIRONMENT}-dbHost" \
                                 --description "Database Host Secret for ${ENVIRONMENT} environment" \
                                 --secret-string $RDS_HOST
