#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR=$SCRIPT_DIR/..

if [ -f $PROJECT_DIR/env/.env ]
then
    source $PROJECT_DIR/env/.env
fi

if ! command -v snyk &> /dev/null
then
    npm install --global snyk
fi

snyk iac test $PROJECT_DIR/python/src/cf_deploy/templates/** \
    --severity-threshold="$SNYK_SEVERITY" \
    --json-file-output=$PROJECT_DIR/reports/snyk/"$(date +'%m-%d-%Y')_report.json"