#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="secret-aws-creds"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/.env

# Example Usage:
# >$     secret-aws-creds --action <create | update>

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --action)
            ACTION="$2"
            shift
            shift 
            ;;
        --help)
            help
            exit 0
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

if [ -z "$ACTION" ]
then
    ACTION="create"
fi

if [ "$ACTION" == "create" ]
then
    aws secretsmanager create-secret --name "${APPLICATION}-AWS-Access-Key" \
                                     --description "API Key for ${APPLICATION} applicatiub" \
                                    --secret-string $AWS_ACCESS_KEY_ID
    aws secretsmanager create-secret --name "${APPLICATION}-AWS-Secret-Key" \
                                     --description "API Key for ${APPLICATION}} environment" \
                                    --secret-string $AWS_SECRET_ACCESS_KEY
    aws secretsmanager create-secret --name "${APPLICATION}-AWS-Account-ID" \
                                     --description "API Key for ${APPLICATION} environment" \
                                    --secret-string $AWS_ACCOUNT_ID
    aws secretsmanager create-secret --name "${APPLICATION}-AWS-Default-Region" \
                                     --description "API Key for ${APPLICATION} environment" \
                                    --secret-string $AWS_DEFAULT_REGION

elif [ "$ACTION" == "update" ]
then
    aws secretsmanager update-secret --secret-id "${APPLICATION}-AWS-Access-Key" \
                                     --description "API Key for ${APPLICATION}-${ENVIRONMENT} environment" \
    aws secretsmanager update-secret --secret-id "${APPLICATION}-AWS-Secret-Key" \
                                     --description "API Key for ${APPLICATION} environment"
    aws secretsmanager update-secret --secret-id "${APPLICATION}-AWS-Account-ID" \
                                     --description "API Key for ${APPLICATION} environment"
    aws secretsmanager update-secret --secret-id "${APPLICATION}-AWS-Default-Region" \
                                     --description "API Key for ${APPLICATION} environment"
fi
