#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="secret-api-key"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/.env

# Execute this step before standing up the Lambda stack if an API key needs to be delivered
# to the Lambda environment.

# Example Usage:
# >$     secret-api-key --environment <Dev | Prod | Test>

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
       key="$1"
       case $key in
                --action)
                    ACTION="$2"
                    shift
                    shift 
                    ;;
                --help)
                    help
                    exit 0
                    ;;
                *)
                    log "Input not understood. See \e[3m--help\e[0m for information on using this command."
                    exit 1
                    ;;
       esac
done

if [ -z "$ACTION" ]
then
    ACTION="create"
fi

RDS_HOST=$(aws cloudformation describe-stacks | jq ".Stacks[] | select(.StackName==\"${RDS_STACK}-${ENVIRONMENT}\")" | jq '.Outputs[0].OutputValue' | tr -d '"')

if [ "$ACTION" == "create" ]
then
    aws secretsmanager create-secret --name "${APPLICATION}-APIUsername" \
                                     --description "API Username for ${APPLICATION} environment" \
                                    --secret-string $API_USERNAME
    aws secretsmanager create-secret --name "${APPLICATION}-APIPassword" \
                                     --description "API Password for ${APPLICATION} environment" \
                                    --secret-string $API_PASSWORD
elif [ "$ACTION" == "update" ]
then
    aws secretsmanager update-secret --secret-id "${APPLICATION}-APIUsername" \
                                     --secret-string $API_USERNAME
    aws secretsmanager create-secret --name "${APPLICATION}-APIPassword" \
                                     --description "API Password for ${APPLICATION} environment" \
                                    --secret-string $API_PASSWORD
fi
