#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="secret-api-key"
SCRIPT_DES=$'Deliver API credentials to \e1[mSecretManager\e0[m. These credentials will be pulled by the pipelines for automated testing for the API and web applications.'
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/env/.env

# Example Usage:
# >$     secret-api-creds --action <create | update>

#   NOTE: `--action` defaults to `create` if not supplied

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --action|-action|--a|-a)
            ACTION="$2"
            shift
            shift 
            ;;
        --help|-help|--h|-h)
            help
            exit 0
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

if [ -z "$ACTION" ]
then
    ACTION="create"
fi

if [ "$ACTION" == "create" ]
then
    aws secretsmanager create-secret --name "${APPLICATION}-AtlassianClientSecret" \
                                     --description "API Username for ${APPLICATION} environment" \
                                    --secret-string $ATLASSIAN_CLIENT_SECRET
    aws secretsmanager create-secret --name "${APPLICATION}-AtlassianSharedSecret" \
                                     --description "API Password for ${APPLICATION} environment" \
                                    --secret-string $ATLASSIAN_SHARED_SECRET
    exit 0
elif [ "$ACTION" == "update" ]
then
    aws secretsmanager update-secret --secret-id "${APPLICATION}-AtlassianClientSecret" \
                                     --secret-string $ATLASSIAN_CLIENT_SECRET
    aws secretsmanager create-secret --name "${APPLICATION}-AtlassianSharedSecret" \
                                    --secret-string $ATLASSIAN_SHARED_SECRET
    exit 0
fi
